name: Tests, Docs, Changelogs, Publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install Repo deps
        run: lerna bootstrap
      - name: Run tests
        run: lerna run test --stream
  changelogs:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git pull
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install Repo deps
        run: lerna bootstrap
      - name: Create Changelogs
        run: lerna run changelog --stream
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 📝 Automated Changelogs
  docs:
    needs: changelogs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - run: git pull
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install Repo deps
        run: lerna bootstrap
      - name: Create Docs
        run: lerna run docs --stream
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 📝 Automated Docs
  publish:
    needs: [changelogs, docs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git pull
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: https://registry.npmjs.org/
          cache: "yarn"
      - name: Install Repo deps
        run: lerna bootstrap
      - name: Configure CI Git User
        run: |
          git config --global user.email ci-bot@github.com
          git config --global user.name GitHub Actions
      - name: Publish Packages
        run: lerna publish patch --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.DREAM_BIT_UTILS_NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
